### ISSUE TITLE
Automatically reconnect to MQTT server

### ISSUE THREAD

**Issue by ArashMotamedi** [kreso975/homebridge-http-sensors-switches#1]
**Is your feature request related to a problem? Please describe:**
Currently, if an MQTT server becomes unavailable or disconnected, the plugin simply errors out with `Connection error: Error: connect ECONNREFUSED. at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)` 

**Describe the solution you'd like:**
Offer a configurable retry mechanism with a default value of 10 seconds. e.g. retry connecting every [x] seconds, where [x] is configurable number of seconds between retries and defaults to 10.  

**Additional context:**
I'm self-hosting the MQTT server, which I occasionally need to restart to change my program logic. As a result, every time my MQTT server restarts, this plugin simply errors out and I need to manually restart HomeBridge to get this plugin working again.

**Comment by kreso975** [comment]
Hi @ArashMotamedi,

Thanks for this. I missed it while developing the plugin. I’ll update it today and release it.
