### ISSUE TITLE
Errors when more then one switch ist defined

### ISSUE THREAD

**Issue by audiopro-git** [kreso975/homebridge-http-sensors-switches#2]
Version: 1.1.6

Hi,

With this configuration: 

```
{
    "devices": [
        {
            "deviceType": "Switch",
            "deviceID": "switch3",
            "deviceName": "NetPowerCtrl 3",
            "deviceManufacturer": "Anel Elektronik",
            "deviceModel": "Hut",
            "deviceFirmwareVersion": "Hut 6.1",
            "urlON": "http://192.168.38.9/?Sw_on=3",
            "urlOFF": "http://192.168.38.9/?Sw_off=3",
            "urlStatus": "http://pi41/api/hut/3",
            "stateName": "power",
            "onStatusValue": "1",
            "offStatusValue": "0"
        },
        {
            "deviceType": "Switch",
            "deviceID": "switch4",
            "deviceName": "NetPowerCtrl 4",
            "deviceManufacturer": "Anel Elektronik",
            "deviceModel": "Hut",
            "deviceFirmwareVersion": "Hut 6.1",
            "urlON": "http://192.168.38.9/?Sw_on=4",
            "urlOFF": "http://192.168.38.9/?Sw_off=4",
            "urlStatus": "http://pi41/api/hut/4",
            "stateName": "power",
            "onStatusValue": "1",
            "offStatusValue": "0"
        }
    ],
    "platform": "HttpSensorsAndSwitches"
}
```
I receive the following errors:

[29/10/2024, 15:05:28] [HttpSensorsAndSwitches] NetPowerCtrl 3 : Error: Cannot find: KEY:  power  in JSON
[29/10/2024, 15:05:33] [HttpSensorsAndSwitches] NetPowerCtrl 3 : Error: Cannot find: KEY:  power  in JSON
[29/10/2024, 15:05:39] [HttpSensorsAndSwitches] NetPowerCtrl 4 : Error: Cannot find: KEY:  power  in JSON
[29/10/2024, 15:05:44] [HttpSensorsAndSwitches] NetPowerCtrl 4 : Error: Cannot find: KEY:  power  in JSON
[29/10/2024, 15:05:49] [HttpSensorsAndSwitches] NetPowerCtrl 4 : Error: Cannot find: KEY:  power  in JSON
[29/10/2024, 15:05:54] [HttpSensorsAndSwitches] NetPowerCtrl 4 : Error: Cannot find: KEY:  power  in JSON
[29/10/2024, 15:05:58] [HttpSensorsAndSwitches] NetPowerCtrl 3 : Error: Cannot find: KEY:  power  in JSON
[29/10/2024, 15:06:04] [HttpSensorsAndSwitches] NetPowerCtrl 4 : Error: Cannot find: KEY:  power  in JSON
[29/10/2024, 15:06:09] [HttpSensorsAndSwitches] NetPowerCtrl 4 : Error: Cannot find: KEY:  power  in JSON

If only one switch is defined, everything works fine.

a.

**Comment by kreso975** [comment]
Hi, I’m currently managing several switches and i think error isn't appearing due to the number of devices. Just to be sure, did you try removing the accessory from the cache? Go to Settings -> Remove Single Accessory -> then delete the ones you modified. Also, the error you’re encountering might indicate that the JSON on your device is missing the KEY  'power'.

**Comment by audiopro-git** [comment]
The return of the JSON value is correct.
After further investigation, I can say that everything works with two or three switches. But as soon as more than one switch is defined, the error messages appear.
Removing the accessory from the cache did not help.

**Comment by kreso975** [comment]
I couldn't replicate the issue. I tested with n switches, and everything worked fine.  

> I can say that everything works with two or three switches. But as soon as more than one switch is defined, the error messages appear.

I don't understand this?

**Comment by audiopro-git** [comment]
I have now changed the answer for the status URL. It seems to be related that I use the same status URL for several switches. The answer looks like this:


```
{
  "power1": "0",
  "power2": "1",
  "power3": "1",
  "power4": "0",
  "power5": "0",
  "power6": "0",
  "power7": "0",
  "power8": "0"
}
```

The configuration is as follows:

```
{
    "name": "HttpSensorsAndSwitches",
    "devices": [
        {
            "deviceType": "Switch",
            "deviceID": "switch3",
            "deviceName": "NetPowerCtrl 3",
            "deviceManufacturer": "Anel Elektronik",
            "deviceModel": "Hut",
            "deviceSerialNumber": "8090218-3",
            "deviceFirmwareVersion": "Hut 6.1",
            "urlON": "http://192.168.38.9/?Sw_on=3",
            "urlOFF": "http://192.168.38.9/?Sw_off=3",
            "urlStatus": "http://pi41/api/hut",
            "stateName": "power3",
            "onStatusValue": "1",
            "offStatusValue": "0"
        },
        {
            "deviceType": "Switch",
            "deviceID": "switch4",
            "deviceName": "NetPowerCtrl 4",
            "deviceManufacturer": "Anel Elektronik",
            "deviceModel": "Hut",
            "deviceSerialNumber": "8090218-4",
            "deviceFirmwareVersion": "Hut 6.1",
            "urlON": "http://192.168.38.9/?Sw_on=4",
            "urlOFF": "http://192.168.38.9/?Sw_off=4",
            "stateName": "power4",
            "onStatusValue": "1",
            "offStatusValue": "0"
        },
        {
            "deviceType": "Switch",
            "deviceID": "switch7",
            "deviceName": "NetPowerCtrl 7",
            "deviceManufacturer": "Anel Elektronik",
            "deviceModel": "Hut",
            "deviceSerialNumber": "8090218-7",
            "deviceFirmwareVersion": "Hut 6.1",
            "urlON": "http://192.168.38.9/?Sw_on=7",
            "urlOFF": "http://192.168.38.9/?Sw_off=7",
            "stateName": "power7",
            "onStatusValue": "1",
            "offStatusValue": "0"
        }
    ],
    "platform": "HttpSensorsAndSwitches"
}
```

The status URL is only entered on the first device and everything works as desired. 

But as soon as I enter the same status URL for all devices, which would actually be logical, the error messages appear.

If this is the desired behaviour, that's fine - you should just point out in the documentation that the status URL only needs to be entered once.

Another logical behaviour would be that the status URL could be entered for each switch, but there should be no error messages.

**Comment by kreso975** [comment]
Hi,
I did fast check using your JSON and here is a sample of my config:
```
{
                    "deviceType": "Switch",
                    "deviceID": "4edfreds1234578",
                    "deviceName": "StripLight",
                    "urlON": "http://192.168.1.73/POWER?state=ON",
                    "urlOFF": "http://192.168.1.73/POWER?state=OFF",
                    "urlStatus": "http://192.168.1.101/test.json",
                    "stateName": "power2",
                    "onStatusValue": "1",
                    "offStatusValue": "0"
                },
                {
                    "deviceType": "Switch",
                    "deviceID": "sdgfsdqweqwea234234gasdg",
                    "deviceName": "249",
                    "urlON": "http://192.168.1.249/POWER?state=ON",
                    "urlOFF": "http://192.168.1.249/POWER?state=OFF",
                    "urlStatus": "http://192.168.1.101/test.json",
                    "stateName": "power7",
                    "onStatusValue": "1",
                    "offStatusValue": "0"
                },
                {
                    "deviceType": "Switch",
                    "deviceID": "sdgfsd123123124125125gasdg",
                    "deviceName": "76",
                    "urlON": "http://192.168.1.76/POWER?state=ON",
                    "urlOFF": "http://192.168.1.76/POWER?state=OFF",
                    "urlStatus": "http://192.168.1.101/test.json",
                    "stateName": "power5",
                    "onStatusValue": "1",
                    "offStatusValue": "0"
                }
```

It's working fine on my 2 different setup Homebridge env. 

It's hard for me to help you because I don't have enough info about your setup. So far, I haven't found any bugs.

**Comment by audiopro-git** [comment]
It seems that my API sometimes answers with a "Request Interupted".
A check in the "[platformSwitchServices.ts](https://github.com/kreso975/homebridge-http-sensors-switches/blob/latest/src/platformSwitchServices.ts)" before line 209 solves the problem.

```
...
});
       
// cancel  previous response if exists
if (response) {
    response.cancel(); 
    }

const data = response.data;
...
```
