### ISSUE TITLE
Support for boolean (true/false) for json results

### ISSUE THREAD

**Issue by RaZiegler** [kreso975/homebridge-http-sensors-switches#3]
When I receive a boolean json result true or false I cannot define this using the UI because it always stores result definitions as text. True or false are saved with double quotes: e.g. "true" which is interpreted as text and not as boolean.
It would nice to have the ability to define boolean as a result option.

**Comment by kreso975** [comment]
Hi @RaZiegler ,
Thank you for your feedback. I'm going to implement support for values that can be String, Boolean, or Number. For Boolean values, I will assume that true means "On" and false means "Off". I'll try to push the changes today. These updates should be backward compatible.

**Comment by kreso975** [comment]
Hi @RaZiegler ,
Let me know if new version works for you.

**Comment by RaZiegler** [comment]
@kreso975 Now it works perfectly for me! Thanks for this fast fix!
